/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SYSTEM
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbogender = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtcosmeticid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcosmeticname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcosmeticquantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcosmeticprice = new javax.swing.JTextField();
        btnaddnewcosmetic = new javax.swing.JButton();
        btnclearcosmetic = new javax.swing.JButton();
        btnexitcosmetic = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbocosmetictype = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtcustomer_id = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblcustomeraddress = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblcustomertelephone = new javax.swing.JLabel();
        lblcustomername = new javax.swing.JLabel();
        lblcustomeremail = new javax.swing.JLabel();
        lblcustomergender = new javax.swing.JLabel();
        lblcustomerage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblcustomername2 = new javax.swing.JLabel();
        lblcustomeraddress2 = new javax.swing.JLabel();
        lblcustomertelephone2 = new javax.swing.JLabel();
        lblcustomeremail2 = new javax.swing.JLabel();
        lblcustomergender2 = new javax.swing.JLabel();
        lblcustomerage2 = new javax.swing.JLabel();
        txtcustomerid2 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Japan Cosmetic Company ");
        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(255, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Add a Customer");

        jLabel2.setText("CustomerID");

        txtcustomerid.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Customer Name");

        txtname.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Customer Address");

        jLabel5.setText("Customer Telephone");

        jLabel6.setText("Customer Email");

        txtaddress.setBackground(new java.awt.Color(204, 204, 204));

        txttelephone.setBackground(new java.awt.Color(204, 204, 204));

        txtemail.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Customer Gender");

        cbogender.setBackground(new java.awt.Color(240, 240, 240));
        cbogender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));

        jLabel8.setText("Customer Age");

        txtage.setBackground(new java.awt.Color(204, 204, 204));

        btnadd.setText("Add New Customer");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbogender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear)
                                .addGap(18, 18, 18)
                                .addComponent(btnexit)))
                        .addGap(0, 304, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbogender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnclear)
                    .addComponent(btnexit))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Cosmetic ID");

        txtcosmeticid.setBackground(new java.awt.Color(240, 240, 240));
        txtcosmeticid.setForeground(new java.awt.Color(255, 0, 51));

        jLabel10.setText("Cosmetic Name");

        txtcosmeticname.setBackground(new java.awt.Color(240, 240, 240));
        txtcosmeticname.setForeground(new java.awt.Color(255, 0, 51));

        jLabel11.setText("Cosmetic Type");

        jLabel12.setText("Cosmetic Quantity");

        txtcosmeticquantity.setBackground(new java.awt.Color(240, 240, 240));
        txtcosmeticquantity.setForeground(new java.awt.Color(255, 0, 51));

        jLabel13.setText("Cosmetic Price");

        txtcosmeticprice.setBackground(new java.awt.Color(240, 240, 240));
        txtcosmeticprice.setForeground(new java.awt.Color(255, 0, 51));

        btnaddnewcosmetic.setText("Add New Cosmetic");
        btnaddnewcosmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewcosmeticActionPerformed(evt);
            }
        });

        btnclearcosmetic.setText("Clear");
        btnclearcosmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearcosmeticActionPerformed(evt);
            }
        });

        btnexitcosmetic.setText("Exit");
        btnexitcosmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitcosmeticActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Add a Cosmetic");

        cbocosmetictype.setBackground(new java.awt.Color(240, 240, 240));
        cbocosmetictype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "eyeliner", "lipstick", "makeup" }));

        jLabel14.setText("Customer ID");

        txtcustomer_id.setBackground(new java.awt.Color(240, 240, 240));
        txtcustomer_id.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                                .addGap(128, 128, 128))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(145, 145, 145)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbocosmetictype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcosmeticquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcosmeticprice, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcustomer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcosmeticname, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcosmeticid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnaddnewcosmetic)
                                .addGap(18, 18, 18)
                                .addComponent(btnclearcosmetic)
                                .addGap(18, 18, 18)
                                .addComponent(btnexitcosmetic)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcosmeticid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtcosmeticname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbocosmetictype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtcosmeticquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtcosmeticprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtcustomer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaddnewcosmetic)
                            .addComponent(btnclearcosmetic)
                            .addComponent(btnexitcosmetic))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Cosmetic", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Customer ID :");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Search Customer  Details");

        txtcid.setBackground(new java.awt.Color(240, 240, 240));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cosmetic_ID", "Cosmetic_Name", "Cosmetic_Type", "Cosmetic_Quantity", "Cosmetic_Price", "Customer_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcustomeremail)
                            .addComponent(lblcustomergender)
                            .addComponent(lblcustomerage)
                            .addComponent(lblcustomertelephone)
                            .addComponent(lblcustomeraddress)
                            .addComponent(lblcustomername))
                        .addGap(468, 468, 468))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblcustomername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcustomeraddress)
                        .addGap(18, 18, 18)
                        .addComponent(lblcustomertelephone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcustomeremail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcustomergender)
                        .addGap(32, 32, 32)
                        .addComponent(lblcustomerage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(0, 103, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Search  Customer's Cosmetic", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Delete Customers's Cosmetic  Details");

        jLabel22.setText("Customer ID :");

        txtcustomerid2.setBackground(new java.awt.Color(240, 240, 240));
        txtcustomerid2.setForeground(new java.awt.Color(255, 0, 0));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(240, 240, 240));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cosmetic_ID", "Cosmetic_Name", "Cosmetic_Type", "Cosmetic_Quantity", "Cosmetic_Price", "Customer_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcustomerage2)
                            .addComponent(lblcustomergender2)
                            .addComponent(lblcustomeremail2)
                            .addComponent(lblcustomertelephone2)
                            .addComponent(lblcustomeraddress2)
                            .addComponent(lblcustomername2)))
                    .addComponent(jLabel15)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txtcustomerid2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtcustomerid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblcustomername2)
                        .addGap(40, 40, 40)
                        .addComponent(lblcustomeraddress2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcustomertelephone2)
                        .addGap(18, 18, 18)
                        .addComponent(lblcustomeremail2)
                        .addGap(18, 18, 18)
                        .addComponent(lblcustomergender2)
                        .addGap(59, 59, 59)
                        .addComponent(lblcustomerage2)
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Delete Customer's Cosmetics", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Reports");

        jButton4.setText("Cosmetic Details According To Gender");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("The Details of cosmetics according to request of cosmetic type");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Cosmetic Price Range Between $50 To $200");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for(int i=model.getRowCount()-1;i>=0;i--){
            model.removeRow(i);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String  icd="";
        for(int i=model.getRowCount()-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        String  CustomerID=txtcid.getText();
        if(CustomerID.length()==0){
            JOptionPane.showMessageDialog(null,"Please Enter Customer ID");
        }
        Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";
        try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String as="SELECT Cosmetic_ID, Cosmetic_Name, Cosmetic_Type, Cosmetic_Quantity,Cosmetic_Price,Customer_ID FROM cosmetics WHERE Customer_ID='"+ CustomerID+"'";
            ResultSet result=stmt.executeQuery(as);
            ResultSetMetaData rmdata=result.getMetaData();
            int count =rmdata.getColumnCount();

            Vector colum_name=new Vector() ;
            Vector data_row=new Vector();
            for(int i=1;i<count;i++)
            {
                colum_name.addElement(rmdata.getColumnName(i));

            }
            model.setColumnIdentifiers(colum_name);
            while(result.next())
            {
                icd=result.getString("Customer_ID");
                data_row=new Vector();
                for(int j=1;j<count;j++){
                    data_row.addElement(result.getString(j));
                }
                model.addRow(data_row);
            }
            jTable1.setModel(model);
             if(!CustomerID.equals(icd)){
                 JOptionPane.showMessageDialog(null," Sorry! No Record Found ");
             }
            /*if(result.next()){

                String s1=result.getString("Customer_ID");
                String s2=result.getString("Customer_Name");
                String s3=result.getString("Customer_Add");
                String s4=result.getString("Customer_Tel");
                String s5=result.getString("Customer_Email");
                String s6=result.getString("Customer_Gender");
                String s7=result.getString("Customer_Age");

                lblcustomeraddress.setText(s3);
                lblcustomertelephone.setText(s4);
                lblcustomeremail.setText(s5);
                lblcustomergender.setText(s6);
                lblcustomerage.setText(s7);

            }
            else
            {
                //  JOptionPane.showMessageDialog(null, "Please Enter the correct Customer ID");

            }*/

        }
        catch(Exception e)
        {
            System.err.println("Error :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String  CustomerID2=txtcustomerid2.getText();

        Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";

        int row = jTable2.getSelectedRow();
        DefaultTableModel model= (DefaultTableModel)jTable2.getModel();

        String selected = model.getValueAt(row, 0).toString();
        selected=CustomerID2;
        if (row >= 0) {

            model.removeRow(row);

            try {
                conn = (Connection) DriverManager.getConnection(url,userName,password);
                PreparedStatement ps = conn.prepareStatement("delete from cosmetics where Customer_ID='"+selected+"' ");
                //PreparedStatement ps=conn.prepareStatement("delete from cosmetics where Customer_ID='"+CustomerID2+"'");
                ps.execute();
            }
            catch (Exception w) {
                JOptionPane.showMessageDialog(this, "Connection Error!");
            }
        }

        /* try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String as="DELETE  from cosmetics where Customer_ID= '" + CustomerID2 +"'";
            stmt=conn.prepareStatement(as);
            stmt.execute(as);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }*/

        /* for(int i=model.getRowCount()-1;i>=0;i--){
            model.removeRow(i);
        }
        txtcustomerid2.setText("");*/
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String cid="";
 for(int i=model.getRowCount()-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        String  CustomerID=txtcustomerid2.getText();
        if(CustomerID.length()==0){
            JOptionPane.showMessageDialog(null,"Please Enter Customer ID");
        }
        Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";
        try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String as="SELECT Cosmetic_ID, Cosmetic_Name, Cosmetic_Type, Cosmetic_Quantity,Cosmetic_Price,Customer_ID FROM cosmetics WHERE Customer_ID='"+ CustomerID+"'";
            ResultSet result=stmt.executeQuery(as);
            ResultSetMetaData rmdata=result.getMetaData();
            int count =rmdata.getColumnCount();

            Vector colum_name=new Vector() ;
            Vector data_row=new Vector();
            for(int i=1;i<count;i++)
            {
                colum_name.addElement(rmdata.getColumnName(i));

            }
            model.setColumnIdentifiers(colum_name);
            while(result.next())
            {
                cid=result.getString("Customer_ID");
                
                data_row=new Vector();
                for(int j=1;j<count;j++){
                    data_row.addElement(result.getString(j));
                }
                model.addRow(data_row);
            }
            jTable2.setModel(model);
              if(!CustomerID.equals(cid)){
                  JOptionPane.showMessageDialog(null, "Sorry! No Record Found");
              }
              
             
            /*if(result.next()){

                String s1=result.getString("Customer_ID");
                String s2=result.getString("Customer_Name");
                String s3=result.getString("Customer_Add");
                String s4=result.getString("Customer_Tel");
                String s5=result.getString("Customer_Email");
                String s6=result.getString("Customer_Gender");
                String s7=result.getString("Customer_Age");

                lblcustomeraddress.setText(s3);
                lblcustomertelephone.setText(s4);
                lblcustomeremail.setText(s5);
                lblcustomergender.setText(s6);
                lblcustomerage.setText(s7);

            }
            else
            {
                //  JOptionPane.showMessageDialog(null, "Please Enter the correct Customer ID");

            }*/

        }
        catch(Exception e)
        {
            System.err.println("Error :" + e.getMessage());
        }

    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnclearcosmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearcosmeticActionPerformed
        // TODO add your handling code here:
        txtcosmeticid.setText("");
        txtcosmeticname.setText("");
        cbocosmetictype.setSelectedIndex(0);
        txtcosmeticquantity.setText("");
        txtcosmeticprice.setText("");
        txtcustomer_id.setText("");
    }//GEN-LAST:event_btnclearcosmeticActionPerformed

    private void btnaddnewcosmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewcosmeticActionPerformed
        // TODO add your handling code here:
        String Cosmetic_ID=txtcosmeticid.getText();
        String Cosmetic_Name=txtcosmeticname.getText();
        String Cosmetic_Type=(String)cbocosmetictype.getSelectedItem();
        String Cosmetic_Quantity=txtcosmeticquantity.getText();
        String Cosmetic_Price=txtcosmeticprice.getText();
        String Customer_ID=txtcustomer_id.getText();
        if(Cosmetic_ID.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Cosmetic ID");
        }
        if(Customer_ID.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Customer ID");
        }
        if(Cosmetic_Name.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Cosmetic  Name");

        }
        if(cbocosmetictype.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Cosmetic Type ");

        }
        if(Cosmetic_Quantity.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Quantity");

        }
        if(Cosmetic_Price.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Price");

        }

        Connection con = null;
        Statement stmt = null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String Password="tmc#";
        try
        {

            Class.forName(driver).newInstance();
            con=DriverManager.getConnection(url, userName, Password);
            stmt=con.createStatement();
            System.out.println("Connected to the database");

            String as = "INSERT INTO cosmetics" +
            "(Cosmetic_ID, Cosmetic_Name, Cosmetic_Type, Cosmetic_Quantity, Cosmetic_Price,Customer_ID) "+
            "VALUES ('"+Cosmetic_ID+"', '"+Cosmetic_Name+"', '"+Cosmetic_Type+"', '"+Cosmetic_Quantity+"', '"+Cosmetic_Price+"','"+Customer_ID+"')";
            System.out.println(as);

            stmt.execute(as);
            con.close();
            JOptionPane.showMessageDialog(null, "Sucessfully Inserted Your Cosmetic");

        }
        catch(Exception e)
        {

            System.err.println("Error:"+ e.getMessage());

        }
        
    }//GEN-LAST:event_btnaddnewcosmeticActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtcustomerid.setText("");
        txtname.setText("");
        txtaddress.setText("");
        txttelephone.setText("");
        txtemail.setText("");
        cbogender.setSelectedIndex(0);
        txtage.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:

        String Customer_ID=txtcustomerid.getText();
        String Customer_Name=txtname.getText();
        String Customer_Address=txtaddress.getText();
        String Customer_Telephone=txttelephone.getText();
        String Customer_Email=txtemail.getText();
        String Customer_Age=txtage.getText();
        String Customer_Gender=(String)cbogender.getSelectedItem();
        if(Customer_ID.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter CustomerID");
        }
        if(Customer_Name.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Name");

        }
        if(Customer_Address.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Address");

        }
        if(Customer_Telephone.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Telephone");

        }
        if(Customer_Email.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Email");

        }
          if(cbogender.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Gender");
        }
        if(Customer_Age.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Age");

        }
      

        Connection con=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String Password="tmc#";
        try
        {

            Class.forName(driver).newInstance();
            con=DriverManager.getConnection(url, userName, Password);
            stmt=con.createStatement();
            System.out.println("Connected to the database");

            String as = "INSERT INTO customer" +
            "(Customer_ID, Customer_Name, Customer_Add, Customer_Tel, Customer_Email,Customer_Gender,Customer_Age) "+
            "VALUES ('"+Customer_ID+"', '"+Customer_Name+"', '"+Customer_Address+"', '"+Customer_Telephone+"', '"+Customer_Email+"','"+Customer_Gender+"','"+Customer_Age+"')";
            System.out.println(as);

            stmt.execute(as);
            con.close();
            JOptionPane.showMessageDialog(null,"Sucessfully Inserted Customer Data");

        }
        catch(Exception e)
        {
            System.err.println("Error:"+ e.getMessage());

        }
        

    }//GEN-LAST:event_btnaddActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnexitcosmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitcosmeticActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitcosmeticActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        report1 r1=new report1();
        r1.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        report2 r2=new report2();
        r2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/raysport";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";

        try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String sele="SELECT Distinct c.Customer_Name,c.Customer_Age,c.Customer_Gender,c.Customer_Tel,c.Customer_Add,c.Customer_Email,co.Cosmetic_Name,co.Cosmetic_Type,co.Cosmetic_Price From customer as c ,cosmetics as co WHERE  co.Cosmetic_Price Between 25 and 100 ";
            ResultSet  res=stmt.executeQuery(sele);
            FileWriter fw=new FileWriter("Report Customer Details For Cosmetic Price Between $50 To 200 .doc" );
            BufferedWriter write=new BufferedWriter(fw);
            DateFormat date=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            java.util.Date da1=new java.util.Date();
            System.out.println(date.format(da1));
            StringBuffer title=new StringBuffer()
            .append("****************************************************\n\n")
            .append("              "+da1+"    \n\n")
            .append("               Japan Cosmetic Ltd            \n \n")
            .append("     Deataisl of Customer's Record  \n\n")
            .append("****************************************************\n\n");

            while(res.next())
            {

                String cosmeticname=res.getString("Cosmetic_Name");
                String  cosmetictype=res.getString("Cosmetic_Type");
                String name=res.getString("Customer_Name");
                String gender=res.getString("Customer_Gender");
                String age=res.getString("Customer_Age");
                String add=res.getString("Customer_Add");
                String tel=res.getString("Customer_Tel");
                String email=res.getString("Customer_Email");
                String price=res.getString("Cosmetic_Price");

                title .append("Customer Name :"+name+"\n")
                .append("Customer Age :"+age+"\n")
                .append("Customer Gender :"+gender+"\n")
                .append("Customer Address :"+add+"\n")
                .append("Customer Telephone :"+tel+"\n")
                .append("Customer Email :"+email+"\n")
                .append("Cosmetic Name :"+cosmeticname+"\n")
                .append("Cosmetic Type :"+cosmetictype+"\n")
                .append("Cosmetic Price :"+price+"\n")

                .append(" "+"\n");

                title.append("****************************************************");

                write.write(title.toString());
                write.close();
                conn.close();

            }

        }
        catch(Exception e)
        {
            System.err.println("Error:"+e.getMessage());

        }

    }//GEN-LAST:event_jButton7ActionPerformed
 DefaultTableModel model=new DefaultTableModel();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddnewcosmetic;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclearcosmetic;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnexitcosmetic;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cbocosmetictype;
    private javax.swing.JComboBox cbogender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblcustomeraddress;
    private javax.swing.JLabel lblcustomeraddress2;
    private javax.swing.JLabel lblcustomerage;
    private javax.swing.JLabel lblcustomerage2;
    private javax.swing.JLabel lblcustomeremail;
    private javax.swing.JLabel lblcustomeremail2;
    private javax.swing.JLabel lblcustomergender;
    private javax.swing.JLabel lblcustomergender2;
    private javax.swing.JLabel lblcustomername;
    private javax.swing.JLabel lblcustomername2;
    private javax.swing.JLabel lblcustomertelephone;
    private javax.swing.JLabel lblcustomertelephone2;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcosmeticid;
    private javax.swing.JTextField txtcosmeticname;
    private javax.swing.JTextField txtcosmeticprice;
    private javax.swing.JTextField txtcosmeticquantity;
    private javax.swing.JTextField txtcustomer_id;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtcustomerid2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttelephone;
    // End of variables declaration//GEN-END:variables
}
