/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;
 
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.*;
import java.io.*;
import java.util.Date;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;


/**
 *
 * @author SYSTEM
 */
public class report1 extends javax.swing.JFrame {

    /**
     * Creates new form report1
     */
    public report1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reports");
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Report For According To Customer's Male");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Report For According To Customer's  Female");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Back To Main");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/japan_cosmetic";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";
         try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String sele="SELECT co.Cosmetic_Name,co.Cosmetic_Type,c.Customer_Gender,c.Customer_Name From cosmetics as co,customer as c where c.Customer_Gender='male'and c.Customer_ID=co.Customer_ID ";
            ResultSet  res=stmt.executeQuery(sele);
            FileWriter fw=new FileWriter("Report For Male.doc" );
            BufferedWriter write=new BufferedWriter(fw);
            DateFormat date=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date da1=new Date();
            System.out.println(date.format(da1));
            StringBuffer title=new StringBuffer()
                    .append("****************************************************\n\n")
                    .append("              "+da1+"    \n\n")
                    .append("               Japan Cosmetic Ltd            \n \n")
                    .append("     Deataisl of Male customer's Cosmetics's Record  \n\n")
                    .append("****************************************************\n\n");
            int malecount=0;
            while(res.next())
            {
                malecount++;
                String cosmeticname=res.getString("Cosmetic_Name");
                String cosmetictype=res.getString("Cosmetic_Type");
                String male=res.getString("Customer_Gender");
                String customername=res.getString("Customer_Name");
                title.append("Csometic Name :"+cosmeticname+"\n")
                 .append("Csometic Type :"+cosmetictype+"\n")
                 .append("Gender :"+male+"\n")
                 .append("Customer Name:"+customername+"\n")
                 .append(" "+"\n");
                
            }
            title.append("Total Number Of  Male Customer :"+malecount+"\n\n")
                  .append("****************************************");
                 
            write.write(title.toString());
            write.close();
            conn.close();
                    
                    
            
            
            
            
            
            
            
            
        }
         catch(Exception e)
         {
             System.err.println("Error:"+e.getMessage());
                     
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           Connection conn=null;
        Statement stmt=null;
        String url="jdbc:mysql://localhost:3306/japan_cosmetic";
        String driver="com.mysql.jdbc.Driver";
        String userName="root";
        String password="tmc#";
         try
        {

            Class.forName(driver).newInstance();
            conn=DriverManager.getConnection(url, userName, password);
            stmt=conn.createStatement();
            System.out.println("Connected to the database");
            String sele="SELECT co.Cosmetic_Name,co.Cosmetic_Type,c.Customer_Gender,c.Customer_Name From cosmetics as co,customer as c where c.Customer_Gender='female'and c.Customer_ID=co.Customer_ID ";
            ResultSet  res=stmt.executeQuery(sele);
            FileWriter fw=new FileWriter("Report For Female.doc" );
            BufferedWriter write=new BufferedWriter(fw);
            DateFormat date=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date da1=new Date();
            System.out.println(date.format(da1));
            StringBuffer title=new StringBuffer()
                    .append("****************************************************\n\n")
                    .append("              "+da1+"    \n\n")
                    .append("               Japan Cosmetic Ltd            \n \n")
                    .append("     Deataisl of Male customer's Cosmetics's Record  \n\n")
                    .append("****************************************************\n\n");
            int malecount=0;
            while(res.next())
            {
                malecount++;
                String cosmeticname=res.getString("Cosmetic_Name");
                String cosmetictype=res.getString("Cosmetic_Type");
                String male=res.getString("Customer_Gender");
                String customername=res.getString("Customer_Name");
                title.append("Csometic Name :"+cosmeticname+"\n")
                 .append("Csometic Type :"+cosmetictype+"\n")
                 .append("Gender :"+male+"\n")
                 .append("Customer Name:"+customername+"\n")
                 .append(" "+"\n");
                
            }
            title.append("Total Number Of  Male Customer :"+malecount+"\n\n")
                  .append("****************************************");
                 
            write.write(title.toString());
            write.close();
            conn.close();
                    
                    
            
            
            
            
            
            
            
            
        }
         catch(Exception e)
         {
             System.err.println("Error:"+e.getMessage());
                     
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main ma=new Main();
        ma.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
